import json

with open('src/services/worldCupCombinations.json', 'r') as f:
    combs = json.load(f)

# combs is a dictionary mapping combination ID (1 to 495) to an array of 8 teams
# the 8 teams are ordered: 1A 1B 1D 1E 1G 1I 1K 1L

# We can find the key (which 8 groups are 3rd place) by looking at the teams in the array.
# For example, for comb 1: ["3E", "3J", "3I", "3F", "3H", "3G", "3L", "3K"]
# The groups are E, J, I, F, H, G, L, K. Sorted, this is E, F, G, H, I, J, K, L.
# Let's map a string of sorted groups (e.g. "EFGHIJKL") to the mapping dictionary.
# Mapping dictionary will be: { "EFGHIJKL": { "1A": "3E", "1B": "3J", ... } }

mapping = {}
for id_str, teams in combs.items():
    groups = sorted([t[1] for t in teams])
    group_str = "".join(groups)

    mapping[group_str] = {
        "1A": teams[0],
        "1B": teams[1],
        "1D": teams[2],
        "1E": teams[3],
        "1G": teams[4],
        "1I": teams[5],
        "1K": teams[6],
        "1L": teams[7],
    }

print(f"Generated mappings for {len(mapping)} unique sets of 3rd place teams.")

# Save to src/services/worldCupBracketLogic.ts
ts_content = """// Autogenerated World Cup Bracket Logic from FIFA Regulations Annexe C

export const thirdPlaceCombinations: Record<string, {
  '1A': string;
  '1B': string;
  '1D': string;
  '1E': string;
  '1G': string;
  '1I': string;
  '1K': string;
  '1L': string;
}> = """ + json.dumps(mapping, indent=2) + """;

export const MATCHES_ROUND_OF_32 = {
    M73: { teamA: '2A', teamB: '2B' },
    M74: { teamA: '1E', teamB: '3rd_1E' }, // Best 3rd place of ABCDF (determined by thirdPlaceCombinations['1E'])
    M75: { teamA: '1F', teamB: '2C' },
    M76: { teamA: '1C', teamB: '2F' },
    M77: { teamA: '1I', teamB: '3rd_1I' }, // Best 3rd place of CDFGH
    M78: { teamA: '2E', teamB: '2I' },
    M79: { teamA: '1A', teamB: '3rd_1A' }, // Best 3rd place of CEFHI
    M80: { teamA: '1L', teamB: '3rd_1L' }, // Best 3rd place of EHIJK
    M81: { teamA: '1D', teamB: '3rd_1D' }, // Best 3rd place of BEFIJ
    M82: { teamA: '1G', teamB: '3rd_1G' }, // Best 3rd place of AEHIJ
    M83: { teamA: '2K', teamB: '2L' },
    M84: { teamA: '1H', teamB: '2J' },
    M85: { teamA: '1B', teamB: '3rd_1B' }, // Best 3rd place of EFGIJ
    M86: { teamA: '1J', teamB: '2H' },
    M87: { teamA: '1K', teamB: '3rd_1K' }, // Best 3rd place of DEIJL
    M88: { teamA: '2D', teamB: '2G' }
};

export const MATCHES_ROUND_OF_16 = {
    M89: { teamA: 'W74', teamB: 'W77' },
    M90: { teamA: 'W73', teamB: 'W75' },
    M91: { teamA: 'W76', teamB: 'W78' },
    M92: { teamA: 'W79', teamB: 'W80' },
    M93: { teamA: 'W83', teamB: 'W84' },
    M94: { teamA: 'W81', teamB: 'W82' },
    M95: { teamA: 'W86', teamB: 'W88' },
    M96: { teamA: 'W85', teamB: 'W87' }
};

export const MATCHES_QUARTER_FINALS = {
    M97:  { teamA: 'W89', teamB: 'W90' },
    M98:  { teamA: 'W93', teamB: 'W94' },
    M99:  { teamA: 'W91', teamB: 'W92' },
    M100: { teamA: 'W95', teamB: 'W96' }
};

export const MATCHES_SEMI_FINALS = {
    M101: { teamA: 'W97', teamB: 'W98' },
    M102: { teamA: 'W99', teamB: 'W100' }
};

export const MATCHES_FINALS = {
    M103: { teamA: 'L101', teamB: 'L102', isThirdPlace: true }, // Third place
    M104: { teamA: 'W101', teamB: 'W102' } // Final
};
"""

with open('src/services/worldCupBracketLogic.ts', 'w') as f:
    f.write(ts_content)
